### PR TITLE
fix: don't quit if readme doesn't exist

### LINKED ISSUE #2242: [Bug] Cannot update due to README path error
I published my first workspace package yesterday (with 2 crates, one, `crustrace` depends on the other, `crustrace-core`)

Upon trying to do so a 2nd time I found I couldn't, and it boiled down to `release-plz update` hitting 

> failed to determine next versions

in turn from 

> failed to retrieve difference of package crustrace-core

because it was trying to "canonicalize path" on a temp copy of the crate at `../../README.md` 😞

```
louis 🌟 ~/dev/crustrace $ release-plz update
2025-05-28T12:31:32.041316Z  INFO using release-plz config file release-plz.toml
2025-05-28T12:31:32.046704Z  INFO downloading packages from cargo registry crates.io
    Updating crates.io index
2025-05-28T12:31:32.248577Z  INFO determining next version for crustrace-core 0.1.0
2025-05-28T12:31:32.925795Z ERROR failed to determine next versions

Caused by:
    0: failed to retrieve difference of package crustrace-core
    1: cannot canonicalize path "/tmp/.tmpPrHoOC/crustrace/crustrace-core/../../README.md"
    2: No such file or directory (os error 2)
Error: failed to determine next versions

Caused by:
    0: failed to retrieve difference of package crustrace-core
    1: cannot canonicalize path "/tmp/.tmpPrHoOC/crustrace/crustrace-core/../../README.md"
    2: No such file or directory (os error 2)
```

https://github.com/release-plz/release-plz/blob/d1cce384842db3e2b0ce053954a18fe070d9d307/crates/release_plz_core/src/command/update/updater.rs#L212

I used what I thought was a common pattern of including my README via

```rust
#![doc = include_str!("../README.md")]
```

I'm not quite sure what is wrong, but it seems like the published package will not be compatible with release-plz 😞

If I remove any reference to the README from code/`Cargo.toml` it still won't `release-plz update`, I interpret this as meaning the published one is the issue (and the debug output suggests it's perhaps when that one is downloaded locally to a temp dir that it fails to canonicalise a double parent path)

### PR DESCRIPTION
**Pull request by lmmx**
- **fix: do not error on README non-existence, just warn**
- Closes #2242
- [x] Tested
- [x] Linted (clippy, fmt)

Added a hint to warning message

> Hint: ensure the path set in Cargo.toml points to a file that exists and is included in the crate.

### CODE REVIEW

**Comment by lmmx** [comment]
Added tests and confirmed they reproduce the bug on the main branch (but pass on this PR)

<details><summary>Click to show failure output on main branch</summary>

```
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.25s
────────────
 Nextest run ID 6bb82aa8-c6ed-4863-be95-9ee7719fcee6 with nextest profile: default
    Starting 157 tests across 10 binaries (4 tests skipped)
        PASS [   0.004s] cargo_utils registry::tests::test_get_registry_env_var_name
        PASS [   0.004s] next_version::all normal::commit_with_breaking_change_increments_minor_version_when_major_is_zero
        PASS [   0.004s] next_version::all normal::commit_with_breaking_change_increments_major_version_when_major_is_zero
        PASS [   0.005s] cargo_utils token::tests::test_parse_cargo_credentials_empty
        PASS [   0.005s] cargo_utils token::tests::test_parse_cargo_credentials_cratesio_only
        PASS [   0.005s] next_version version_increment::tests::returns_true_for_matching_custom_type
        PASS [   0.005s] next_version version_increment::tests::returns_false_for_empty_commits_list
        PASS [   0.005s] git_cmd tests::changes_files_except_typechanges_are_detected
        PASS [   0.006s] cargo_utils token::tests::test_parse_cargo_credentials_both
        PASS [   0.006s] next_version::all normal::commit_with_breaking_change_increments_major_version
        PASS [   0.006s] next_version version_increment::tests::returns_false_for_non_custom_commit_types
        PASS [   0.004s] next_version::all normal::commit_with_fix_semver_prefix_increments_patch_version
        PASS [   0.004s] next_version::all normal::commit_with_custom_minor_increment_regex_increments_minor_version
        PASS [   0.004s] next_version::all normal::commit_with_feat_semver_prefix_increments_minor_version_when_major_is_zero
        PASS [   0.004s] next_version::all normal::commit_with_feat_semver_prefix_increments_patch_version_when_major_is_zero
        PASS [   0.004s] next_version::all normal::commit_with_feat_semver_prefix_increments_patch_version
        PASS [   0.004s] next_version::all normal::commit_with_scope
        PASS [   0.005s] next_version::all normal::commit_with_custom_major_increment_regex_increments_major_version
        PASS [   0.003s] next_version::all normal::commit_with_scope_whitespace
        PASS [   0.004s] next_version::all normal::commit_with_scope_minor
        PASS [   0.003s] next_version::all pre_release::commit_with_breaking_change_increments_pre_release_version
        PASS [   0.004s] next_version::all normal::commit_without_semver_prefix_increments_patch_version
        PASS [   0.004s] next_version::all pre_release::dot_1_is_added_to_character_identifier_in_pre_release
        PASS [   0.005s] next_version::all pre_release::dot_1_is_added_to_last_identifier_in_pre_release
        PASS [   0.005s] next_version::all pre_release::commit_without_semver_prefix_increments_pre_release_version
        PASS [   0.005s] next_version::all pre_release::dot_1_is_added_to_unversioned_pre_release
        PASS [   0.021s] git_cmd tests::inexistent_previous_commit_detected
        PASS [   0.025s] git_cmd tests::clean_project_is_recognized
        PASS [   0.025s] git_cmd tests::dirty_project_is_recognized
        PASS [   0.025s] git_cmd tests::is_branch_of_commit_detected_correctly
        PASS [   0.027s] git_cmd tests::current_commit_is_retrieved
        PASS [   0.030s] git_cmd tests::non_existing_tag_is_recognized
        PASS [   0.031s] git_cmd tests::existing_tag_is_recognized
        PASS [   0.035s] git_cmd tests::tags_are_retrieved
        PASS [   0.047s] git_cmd tests::previous_commit_is_retrieved
        PASS [   0.165s] release-plz::all completion_test::test_generate_completions
        PASS [   2.292s] release-plz::all helpers::gitea::gitea_new::can_create_gitea_repository
        PASS [   4.470s] release-plz::all release::release_plz_does_not_release_a_new_project_if_release_always_is_false
        PASS [   5.413s] release-plz::all changelog::can_generate_single_changelog_for_multiple_packages_locally
        PASS [   5.759s] release-plz::all changelog::raw_message_contains_entire_commit_message
        PASS [   6.401s] release-plz::all changelog::release_plz_adds_changelog_on_new_project
        PASS [   6.510s] release-plz::all release_pr::release_plz_doesnt_add_invalid_labels_to_release_pr
        PASS [   6.842s] release-plz::all release::release_plz_does_not_releases_twice
        PASS [   6.985s] release-plz::all changelog::release_plz_releases_a_new_project
        FAIL [   4.768s] release-plz::all release_pr::release_plz_handles_invalid_readme_path_gracefully
──── STDOUT:             release-plz::all release_pr::release_plz_handles_invalid_readme_path_gracefully

running 1 test
New user 'sjyomula' has been successfully created!
test release_pr::release_plz_handles_invalid_readme_path_gracefully ... FAILED

failures:

failures:
    release_pr::release_plz_handles_invalid_readme_path_gracefully

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 35 filtered out; finished in 4.76s

──── STDERR:             release-plz::all release_pr::release_plz_handles_invalid_readme_path_gracefully
Cloning into 'dobraxpw'...

thread 'release_pr::release_plz_handles_invalid_readme_path_gracefully' panicked at /home/louis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5:
Unexpected failure.
code=1
stderr=``````
    Blocking waiting for file lock on package cache
    Updating `test-registry` index
     Running `git fetch --no-tags --verbose --force --update-head-ok \'http://localhost:3000/sjyomula/_cargo-index.git\' \'+HEAD:refs/remotes/origin/HEAD\'`
POST git-upload-pack (279 bytes)
POST git-upload-pack (167 bytes)
From http://localhost:3000/sjyomula/_cargo-index
 * [new ref]         HEAD       -> origin/HEAD
\x1b[2m2025-06-07T12:26:00.966755Z\x1b[0m \x1b[31mERROR\x1b[0m \x1b[2mrelease_plz\x1b[0m\x1b[2m:\x1b[0m \x1b[2mcrates/release_plz/src/main.rs\x1b[0m\x1b[2m:\x1b[0m\x1b[2m22:\x1b[0m failed to update packages

Caused by:
    0: failed to determine next versions
    1: failed to retrieve difference of package dobraxpw
    2: cannot canonicalize path \"/tmp/.tmpl879YJ/dobraxpw/../../README.md\"
    3: No such file or directory (os error 2)
Error: failed to update packages

Caused by:
    0: failed to determine next versions
    1: failed to retrieve difference of package dobraxpw
    2: cannot canonicalize path \"/tmp/.tmpl879YJ/dobraxpw/../../README.md\"
    3: No such file or directory (os error 2)
```
```
command=`cd "/tmp/.tmplIJu9G/dobraxpw" && RELEASE_PLZ_LOG="ERROR" "/home/louis/dev/release-plz/target/debug/release-plz" "release-pr" "--verbose" "--git-token" "7d1b1f81e944a90cab53ff2f8a8147e584e347f1" "--forge" "gitea" "--registry" "test-registry" "--output" "json"`
code=1
stdout=""
stderr=```
    Blocking waiting for file lock on package cache
    Updating `test-registry` index
     Running `git fetch --no-tags --verbose --force --update-head-ok \'http://localhost:3000/sjyomula/_cargo-index.git\' \'+HEAD:refs/remotes/origin/HEAD\'`
POST git-upload-pack (279 bytes)
POST git-upload-pack (167 bytes)
From http://localhost:3000/sjyomula/_cargo-index
 * [new ref]         HEAD       -> origin/HEAD
\x1b[2m2025-06-07T12:26:00.966755Z\x1b[0m \x1b[31mERROR\x1b[0m \x1b[2mrelease_plz\x1b[0m\x1b[2m:\x1b[0m \x1b[2mcrates/release_plz/src/main.rs\x1b[0m\x1b[2m:\x1b[0m\x1b[2m22:\x1b[0m failed to update packages

Caused by:
    0: failed to determine next versions
    1: failed to retrieve difference of package dobraxpw
    2: cannot canonicalize path \"/tmp/.tmpl879YJ/dobraxpw/../../README.md\"
    3: No such file or directory (os error 2)
Error: failed to update packages

Caused by:
    0: failed to determine next versions
    1: failed to retrieve difference of package dobraxpw
    2: cannot canonicalize path \"/tmp/.tmpl879YJ/dobraxpw/../../README.md\"
    3: No such file or directory (os error 2)
```


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

  Cancelling due to test failure: 19 tests still running
        PASS [   7.101s] release-plz::all release::release_info_contains_prs_in_changelog
        PASS [   7.159s] release-plz::all release::release_plz_releases_a_new_project_with_custom_release
        PASS [   7.262s] release-plz::all release::release_plz_releases_a_new_project_with_custom_tag_name
        PASS [   7.456s] release-plz::all changelog::can_generate_single_changelog_for_multiple_packages_in_pr
        PASS [   7.564s] release-plz::all changelog::release_plz_adds_custom_changelog
        PASS [   8.172s] release-plz::all changelog::release_plz_does_not_open_release_pr_if_there_are_no_release_commits
        FAIL [   3.692s] release-plz::all release_pr::release_plz_handles_nonexistent_readme_path_in_cargo_toml
──── STDOUT:             release-plz::all release_pr::release_plz_handles_nonexistent_readme_path_in_cargo_toml

running 1 test
New user 'ikhfyihr' has been successfully created!
test release_pr::release_plz_handles_nonexistent_readme_path_in_cargo_toml ... FAILED

failures:

failures:
    release_pr::release_plz_handles_nonexistent_readme_path_in_cargo_toml

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 35 filtered out; finished in 3.68s

──── STDERR:             release-plz::all release_pr::release_plz_handles_nonexistent_readme_path_in_cargo_toml
Cloning into 'ailvamgj'...

thread 'release_pr::release_plz_handles_nonexistent_readme_path_in_cargo_toml' panicked at /home/louis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5:
Unexpected failure.
code=1
stderr=``````
    Updating `test-registry` index
     Running `git fetch --no-tags --verbose --force --update-head-ok \'http://localhost:3000/ikhfyihr/_cargo-index.git\' \'+HEAD:refs/remotes/origin/HEAD\'`
POST git-upload-pack (279 bytes)
POST git-upload-pack (167 bytes)
From http://localhost:3000/ikhfyihr/_cargo-index
 * [new ref]         HEAD       -> origin/HEAD
\x1b[2m2025-06-07T12:26:02.072410Z\x1b[0m \x1b[31mERROR\x1b[0m \x1b[2mrelease_plz\x1b[0m\x1b[2m:\x1b[0m \x1b[2mcrates/release_plz/src/main.rs\x1b[0m\x1b[2m:\x1b[0m\x1b[2m22:\x1b[0m failed to update packages

Caused by:
    0: failed to determine next versions
    1: failed to retrieve difference of package ailvamgj
    2: cannot canonicalize path \"/tmp/.tmpXXXMuD/ailvamgj/nonexistent-readme.md\"
    3: No such file or directory (os error 2)
Error: failed to update packages

Caused by:
    0: failed to determine next versions
    1: failed to retrieve difference of package ailvamgj
    2: cannot canonicalize path \"/tmp/.tmpXXXMuD/ailvamgj/nonexistent-readme.md\"
    3: No such file or directory (os error 2)
```
```
command=`cd "/tmp/.tmp3HeccI/ailvamgj" && RELEASE_PLZ_LOG="ERROR" "/home/louis/dev/release-plz/target/debug/release-plz" "release-pr" "--verbose" "--git-token" "17eb94319cf43c62cc9e02c6b6b35584b18c42e2" "--forge" "gitea" "--registry" "test-registry" "--output" "json"`
code=1
stdout=""
stderr=```
    Updating `test-registry` index
     Running `git fetch --no-tags --verbose --force --update-head-ok \'http://localhost:3000/ikhfyihr/_cargo-index.git\' \'+HEAD:refs/remotes/origin/HEAD\'`
POST git-upload-pack (279 bytes)
POST git-upload-pack (167 bytes)
From http://localhost:3000/ikhfyihr/_cargo-index
 * [new ref]         HEAD       -> origin/HEAD
\x1b[2m2025-06-07T12:26:02.072410Z\x1b[0m \x1b[31mERROR\x1b[0m \x1b[2mrelease_plz\x1b[0m\x1b[2m:\x1b[0m \x1b[2mcrates/release_plz/src/main.rs\x1b[0m\x1b[2m:\x1b[0m\x1b[2m22:\x1b[0m failed to update packages

Caused by:
    0: failed to determine next versions
    1: failed to retrieve difference of package ailvamgj
    2: cannot canonicalize path \"/tmp/.tmpXXXMuD/ailvamgj/nonexistent-readme.md\"
    3: No such file or directory (os error 2)
Error: failed to update packages

Caused by:
    0: failed to determine next versions
    1: failed to retrieve difference of package ailvamgj
    2: cannot canonicalize path \"/tmp/.tmpXXXMuD/ailvamgj/nonexistent-readme.md\"
    3: No such file or directory (os error 2)
```


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

        PASS [   9.064s] release-plz::all release_pr::changelog_is_not_updated_if_version_already_exists_in_changelog
        PASS [   9.993s] release-plz::all release_pr::release_plz_adds_labels_to_release_pr
        PASS [  10.129s] release-plz::all release::release_plz_releases_after_release_pr_merged
        PASS [   4.107s] release-plz::all release_pr::release_plz_opens_pr_with_default_config
        PASS [   3.629s] release-plz::all release_pr::release_plz_should_fail_for_multi_package_pr
        PASS [   4.136s] release-plz::all release_pr::release_plz_opens_pr_with_two_packages_and_default_config
        PASS [  10.919s] release-plz::all changelog::pr_link_is_expanded
        PASS [  13.947s] release-plz::all release_pr::release_plz_detects_edited_readme_cargo_toml_field
        PASS [  13.968s] release-plz::all release_pr::release_plz_detects_symlink_package_changes
        PASS [   8.875s] release-plz::all release_pr::release_plz_opens_pr_with_breaking_changes
        PASS [   9.232s] release-plz::all release_pr::release_plz_opens_pr_without_breaking_changes
        PASS [  11.368s] release-plz::all release_pr::release_plz_honors_features_always_increment_minor_flag
────────────
     Summary [  16.790s] 64/157 tests run: 62 passed, 2 failed, 4 skipped
        FAIL [   4.768s] release-plz::all release_pr::release_plz_handles_invalid_readme_path_gracefully
        FAIL [   3.692s] release-plz::all release_pr::release_plz_handles_nonexistent_readme_path_in_cargo_toml
warning: 93/157 tests were not run due to test failure (run with --no-fail-fast to run all tests, or run with --max-fail)
error: test run failed
```

</details>

File: crates/release_plz_core/src/package_compare.rs [hunk 1]
```diff
@@ -176,9 +176,17 @@ pub fn local_readme_override(
     package
         .readme
         .as_ref()
-        .map(|readme| {
+        .and_then(|readme| {
             let readme_path = local_package_path.join(readme);
-            fs_utils::canonicalize_utf8(&readme_path)
+            if !readme_path.exists() {
+                tracing::warn!(
+                    "README path '{}' doesn't exist for package '{}', its canonical path will be None",
```
Comment (marcoieni) [inline crates/release_plz_core/src/package_compare.rs]: "its canonical path will be None" is something that is very contributor oriented.
Imo we should write:
- what's the cause
- how can the user improve the current situation

wdyt?

Comment (lmmx) [reply crates/release_plz_core/src/package_compare.rs]: True, the error is really saying “we’re going to ignore the README path {value} configured in the metadata for package {package_name}”, the fact it’s set to None internally is just an implementation detail. 

I’d hope that it already conveys the cause (“README path doesn’t exist”), but agree that the call to action is absent. To improve the latter I’d add

> Hint: ensure the path set in Cargo.toml points to a file that exists and is included in the crate.

Comment (marcoieni) [reply crates/release_plz_core/src/package_compare.rs]: Yeah, this would be great, thanks!

File: crates/release_plz_core/src/package_compare.rs [hunk 2]
```diff
@@ -176,9 +176,17 @@ pub fn local_readme_override(
     package
         .readme
         .as_ref()
-        .map(|readme| {
+        .and_then(|readme| {
             let readme_path = local_package_path.join(readme);
-            fs_utils::canonicalize_utf8(&readme_path)
+            if !readme_path.exists() {
+                tracing::warn!(
+                    "README path '{}' doesn't exist for package '{}', its canonical path will be None.\n\nHint: ensure the path set in Cargo.toml points to a file that exists and is included in the crate.",
```
Comment (marcoieni) [inline crates/release_plz_core/src/package_compare.rs]:
```suggestion
                    "README path '{}' doesn't exist for package '{}'.\n\nHint: ensure the path set in Cargo.toml points to a file that exists and is included in the crate.",
```

File: crates/release_plz_core/src/package_compare.rs [hunk 3]
```diff
@@ -176,9 +176,17 @@ pub fn local_readme_override(
     package
         .readme
         .as_ref()
-        .map(|readme| {
+        .and_then(|readme| {
             let readme_path = local_package_path.join(readme);
-            fs_utils::canonicalize_utf8(&readme_path)
+            if !readme_path.exists() {
+                tracing::warn!(
+                    "README path '{}' doesn't exist for package '{}'.\n\nHint: ensure the path set in Cargo.toml points to a file that exists and is included in the crate.",
```
Comment (marcoieni) [inline crates/release_plz_core/src/package_compare.rs]:
```suggestion
                    "README path '{}' doesn't exist for package '{}'. Hint: ensure the path set in Cargo.toml points to a file that exists and is included in the crate.",
```
