### PR TITLE
fix: recognize gitea-actions as bot account

### LINKED ISSUE #2345: `release-pr` doesn't detect bots on Forgejo
## Bug description

`release-plz` creates a new PR if the old PR contains commits from non-bot users. However, this is implemented by checking if their login name ends with "[bot]".

On Forgejo (and I assume Gitea as well), using `--git-token $GITHUB_TOKEN`,  the PR is posted by an account named "forgejo-actions". As a result, it thinks it's a contributor and closes the PR to preserve its history.

- Would you like to work on a fix? [y/n] Yeah, if the fix is simple enough, depending on the approach, eg. a blacklist such as `["forgejo-actions", "gitea-actions"]`

## To Reproduce

1. Run `release-plz release-pr` on a Gitea/Forgejo repo
2. Run it again

## Expected behavior

The existing PR is updated as long as no actual human touched it.

## Screenshots

N/A

## Environment

- OS: `marcoieni/release-plz` Docker image
- release-plz version: 0.3.141

### PR DESCRIPTION
**Pull request by darkwater**
Fixes #2345

### CODE REVIEW

File: crates/release_plz_core/src/git/forge.rs [hunk 1]
```diff
@@ -951,12 +955,25 @@ pub struct GitHubCommitAuthor {
...
+            if author.login.ends_with("[bot]") {
+                return false;
+            }
+
+            if forge == ForgeType::Gitea && author.id == -2 {
+                // gitea-actions account
+                return false;
+            }
+
+            true
```
Comment (marcoieni) [inline crates/release_plz_core/src/git/forge.rs]:
```suggestion
            let is_gitea_actions_account = forge == ForgeType::Gitea && author.id == -2;
            let is_bot = author.login.ends_with("[bot]") || is_gitea_actions_account;
            !is_bot
```
simpler 👍

**Review by marcoieni — APPROVED** [review]
